server:
  port: 12000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.204.132:3306/guli_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:/mapper/oms/*.xml
